name: Telegram Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install python-telegram-bot

- name: Run bot
  env:
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  run: |
    timeout 300 python main.py
